### ISSUE TITLE
Peer name xxx.xxx.xxx.xxx is not in peer certificate

### ISSUE THREAD

**Issue by 0x5143** [deckarep/EasyCert#1]
I use my macbook to generate cert files with ca=China and host=192.168.1.51.
In server side it runs normal, but in client side with myCA.cer, it report "Peer name 192.168.1.51 is not in peer certificate".

Can help me?

**Comment by jjhesk** [comment]
we need some more sample usages. @deckarep

**Comment by 0x5143** [comment]
It happen too long ago, so I have forgot what happen. I will close this issue until I found it again.
